### ISSUE TITLE
pip install fails with lpu

### ISSUE THREAD

**Issue by novski** [akivajp/dnsmasq-webconf#3]
MacOS 12.6 in venv with Python 3.10.9 and pip 22.3.1

first got this:
```
pip install bottle jinja2 numpy lpu
Collecting bottle
  Using cached bottle-0.12.23-py3-none-any.whl (90 kB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting numpy
  Using cached numpy-1.24.1-cp310-cp310-macosx_11_0_arm64.whl (13.9 MB)
Collecting lpu
  Using cached lpu-0.2.10.tar.gz (2.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/sf/yfrzcwy91jz9m0cc0y82g_k00000gn/T/pip-install-h3etx1wi/lpu_4c035c6bd5354315949febd2d4f827b1/setup.py", line 13, in <module>
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

then tried to install without lpu and add lpu after numpy:
see here [link](https://pastebin.com/V18KUkf1).

**Comment by akivajp** [comment]
Sorry for the late reply. The package "lpu" is no more needed.
